### ISSUE TITLE
Allow bigger image upload

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#11]
Allow bigger images upload. Habría algún addon o similar para comprimir/reducir las imágenes una vez subidas y no tener que editarlas en el ordenador (hasta cierto tamaño, pero que puedan subirse imagenes en HD)

**Comment by noauthoritybuturself** [comment]
qual é o máximo de MB que pretendes?

**Comment by noauthoritybuturself** [comment]
bump @watchoutfreedom

**Comment by watchoutfreedom** [comment]
puede permitirse varios mb y que se comprima al subir? @noauthoritybuturself

**Comment by noauthoritybuturself** [comment]
penso que o wordpress já faz isso automaticamente :) retiro todas as restriçoes?

**Comment by watchoutfreedom** [comment]
ok!!

**Comment by noauthoritybuturself** [comment]
hecho. vou por closed, abre outra vez se nao funcionar.
