### ISSUE TITLE
Añadir paginación en home

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#13]
Añadir paginación de scroll a las listas para que se carguen artículos más antiguos cuando vayas  bajando

**Comment by noauthoritybuturself** [comment]
lazy scroll (ajax) ou paginação?

**Comment by noauthoritybuturself** [comment]
não me faz sentido fazer isso na home pois a home tem uma quantidade de artigos fixa, não? (um de cada tipo)
mas posso adicionar às outras listas

**Comment by noauthoritybuturself** [comment]
todos os artigos independentemente do tipo? produtos, posts, activities, etc?

**Comment by noauthoritybuturself** [comment]
podes verificar? faço também nas outras listagens?

**Comment by watchoutfreedom** [comment]
> podes verificar @watchoutfreedom ? faço também nas outras listagens?

Si parece que funciona! en el resto de listas también por favor. Muchas gracias

**Comment by noauthoritybuturself** [comment]
ok, closed
