### ISSUE TITLE
Cambiar estructura h1/enlaces

### ISSUE THREAD

**Issue by gruncho** [watchoutfreedom/wof_wp#14]
Necesitamos que los formatos de los títulos vayan así siempre:

1. Solo 1 `<h1>` por página
2. Los enlaces van por dentro de los `<h1>`

## Solo un h1 por página

Solo hay un `<h1>` por página, en la home sin ir más lejos hay h1 en cada listado de post, dentro de cada post el h1 siempre es el título y debajo no hay nada más.

Poned un `<h2>` en los listados de posts seas cuales sean.

## Enlaces dentro de los hX

Creo que es conveniente que cambiemos los `<h1><a href=""></a></h1>` y no como está ahora, que es al revés, un enlace y dentro un`<h1>`.

**Comment by watchoutfreedom** [comment]
> Necesitamos que los formatos de los títulos vayan así siempre:
> 
> 1. Solo 1 `<h1>` por página
> 2. Los enlaces van por dentro de los `<h1>`
> 
> ## Solo un h1 por página
> 
> Solo hay un `<h1>` por página, en la home sin ir más lejos hay h1 en cada listado de post, dentro de cada post el h1 siempre es el título y debajo no hay nada más.
> 
> Poned un `<h2>` en los listados de posts seas cuales sean.
> 
> ## Enlaces dentro de los hX
> Creo que es conveniente que cambiemos los `<h1><a href=""></a></h1>` y no como está ahora, que es al revés, un enlace y dentro un`<h1>`.

Alex te refieres a que en el listado cada post vaya con su H1, pero después en la pagina de post solo haya un h1? o incluso en el listado solo puede haber un h1 en toda la pagina (en su caso los titulos de los posts en el listado qué serían?)
