### ISSUE TITLE
Single post sin cabeceras

### ISSUE THREAD

**Issue by gruncho** [watchoutfreedom/wof_wp#15]
Los proyectos no tienen h1 (osea, no existe cabecera)

Ejemplo
https://dev.watchoutfreedom.com/activity/watch-out-bitcoin-2022/

**Comment by watchoutfreedom** [comment]
> existe uma cabeceira por baixo da galeria igual ao design

Creo que la cabecera debería tener un h1 html tag es a lo que se refiere

**Comment by noauthoritybuturself** [comment]
sim, mas no post single tiene um H1 depois da galeria.

na lista de blogs tem um H2 dentro desse a href que colaste aqui. pode ser um H1 em vez de H2, não há problema em repetir H1 embora não foi isso que foi pedido em #14

**Comment by watchoutfreedom** [comment]
vale, entonces lo dejamos a ver qué dice @gruncho
