### ISSUE TITLE
Change main menu structure

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#20]
Siento que cambiemos esto pero Alex lo ha apuntado como un problema tener un menu principal tan amplio y creo que tiene razón. Vamos a cambiar los nombres del menú principal  e incluir algunas de las páginas como secciones de otras que aparezcan en el submenu en lugar del menu. Así la estructura quedaría:

- (Home) CONOCE: Es la home como ya la teníamos, aquí aparecerían los proyectos como enlace en el submenu.

- (Blog) DEBATE: el blog tal y como estaba
-  (Servicios) CONTRATA : la pagina de servicios como estaba
- (Colabora) COLABORA: (Esta página va a cambiar) Incluye la descripción del about y los enlaces a colabora y donar como la colaborar antigua. Tiene enlaces a la página COMUNIDAD, TIENDA 
- ENTRAR
<img width="937" alt="Captura de Pantalla 2023-01-27 a las 16 30 57" src="https://user-images.githubusercontent.com/23015314/215128102-83e53206-fd17-4dd4-abb4-6938dbf69a0f.png">

**Comment by watchoutfreedom** [comment]
PAGINA COLABORA
<img width="238" alt="Captura de Pantalla 2023-01-27 a las 18 34 18" src="https://user-images.githubusercontent.com/23015314/215155353-633fa454-fa3e-4c19-b8f0-97467bdd5d2b.png">

**Comment by noauthoritybuturself** [comment]
atualizei a página colabora. deveria também atualizar o menu?

**Comment by watchoutfreedom** [comment]
> atualizei a página colabora. deveria também atualizar o menu?

Si gracias
