### ISSUE TITLE
La sección del menú secundario debería permitir el scroll vertical a partir de x entradas

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#25]
En esta sección habrá muchos enlaces, como en el blog en el que habrá una lista de tags. Tanto en móvil como en desktop debería tener un overflow que permitiera el scroll. En móvil tanto el menú principal como el secundario

![Captura de Pantalla 2023-02-14 a las 17 48 24](https://user-images.githubusercontent.com/23015314/218803333-69e984ea-1853-4055-9240-891b4dafb4f6.jpg)

**Comment by noauthoritybuturself** [comment]
merged with #45
