### ISSUE TITLE
falta la opcion de suscripcion

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#26]
Falta la página de suscripción y enlazarla en la página COLABORA

**Comment by watchoutfreedom** [comment]
![Captura de Pantalla 2023-02-15 a las 11 58 54](https://user-images.githubusercontent.com/23015314/219009422-8c979d1a-6f61-4899-8316-875e4fbcad08.JPG)

**Comment by noauthoritybuturself** [comment]
https://dev.watchoutfreedom.com/subscribe/

já está criada, onde linko em Colabora? e que botões sao aqueles sem label?

**Comment by watchoutfreedom** [comment]
Si, ya lo he cambiado. El link estaría en la home, en la parte baja de la
pantalla en movil y en el submenu en desktop. Los dos botones después de
confirmar suscripción van a colabora y otro a volver.

**Comment by noauthoritybuturself** [comment]
hecho!
