### ISSUE TITLE
Mostrar al final del artículo del blog los artículos de respuesta

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#28]
Si un artículo del blog tiene respuestas, mostrar al final la lista de ellas. 

También parece que al intentar publiucar un respuesta sin estar logeado, no te pide logearte sino que elimina tu respuesta.

**Comment by watchoutfreedom** [comment]
También parece que se publica la respuesta pero se elimina el contenido. Solo aparece el título. Además no se hace referencia en la respuesta al artículo original al que se respondió

**Comment by noauthoritybuturself** [comment]
estou a tentar resolver este problema. o ACF não está a conseguir guardar os inputs no frontend. em breve espero solucionar.

**Comment by noauthoritybuturself** [comment]
resolvido!
