### ISSUE TITLE
Poner el autor al final del artículo en la lista del blog

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#32]
El autor en la vista de lista del blog se ve al principio. debería verse el autor después. En el caso de respuestas, encima del título sí debería verse Ën respuesta a¨ con la referencia al artículo original al que responde

**Comment by noauthoritybuturself** [comment]
![image](https://user-images.githubusercontent.com/12964924/226617925-ce0be2a7-2584-41e8-81d2-3e9644ca8bc8.png)
não compreendo, o autor já parece estar no final?
