### ISSUE TITLE
Los filtros no funcionan en algunos casos

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#33]
Los filtros de tipos de posts en la seccion debate y categorías no funcionan a veces
![Captura de Pantalla 2023-03-31 a las 20 35 12](https://user-images.githubusercontent.com/23015314/229202570-c688435a-66e4-4756-b9ec-cf4a87c88e71.jpg)

**Comment by watchoutfreedom** [comment]
tampoco algunos filtros de tags e debate y categorias en el solicita

**Comment by noauthoritybuturself** [comment]
resolvido!
