### ISSUE TITLE
how to connect the website to email so it send alerts

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#36]
What do we need to start the process to send alerts to admins and users.

**Comment by noauthoritybuturself** [comment]
which alerts would you like? i think it already sends emails, no?

**Comment by noauthoritybuturself** [comment]
ok, i set up a plugin for SMTP. you can set it up here:
https://dev.watchoutfreedom.com/wp-admin/admin.php?page=wp-mail-smtp-setup-wizard
