### ISSUE TITLE
En algunas entradas aparece el boton editar en lugar de responder, sin estar logeado

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#39]
![Captura de Pantalla 2023-04-12 a las 17 11 45](https://user-images.githubusercontent.com/23015314/231502052-46ba156e-e808-4882-9253-51425bd64125.jpg)

**Comment by noauthoritybuturself** [comment]
como criaste esse post? isso está a acontecer porque o post não tem autor, que não deveria.

**Comment by watchoutfreedom** [comment]
lo creé normalmente desde el editor, no sé por qué no tiene autor, quizás al cambiar el nombre?

**Comment by noauthoritybuturself** [comment]
vou fechar por enquanto até voltar acontecer
