### ISSUE TITLE
Menu de tags en la pagina del blog

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#4]
Igual que hay una lista de tipos en la pagina servicios, tener una lista de tags en la pagina del blog.
<img width="654" alt="Captura de Pantalla 2023-01-17 a las 18 13 24" src="https://user-images.githubusercontent.com/23015314/212966367-3c8595af-efc5-4cf8-822e-9ceb4b011e25.png">

**Comment by noauthoritybuturself** [comment]
podes verificar?

**Comment by watchoutfreedom** [comment]
Hecho :). Cuando le doy a un tag, desaparece el menú, y el ALL redirige a la home, no al blog

**Comment by noauthoritybuturself** [comment]
hecho
