### ISSUE TITLE
Eliminar cuentas noreales para que no aparezcan en la pagina de comunidad

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#5]
Hay cuentas a las que se ve el email en la pagina de comunidad, habria que pasarlo a  nombre o eliminar ese usuario. Habría la posibilidad de marcar usuarios para que no aparezcan en la pagina comunidad?

**Comment by noauthoritybuturself** [comment]
removi os users que mencionaste e adicionei um field "hide from comunity page" a todos os users
