### ISSUE TITLE
Users field is broken

### ISSUE THREAD

**Issue by watchoutfreedom** [watchoutfreedom/wof_wp#9]
No puedo busar users en el campo users de las actividades, no sé si pasa en otros posts también

**Comment by noauthoritybuturself** [comment]
bump @watchoutfreedom

**Comment by watchoutfreedom** [comment]
deberian poder ser admin, editor, author. Contributor no

**Comment by watchoutfreedom** [comment]
contributor role cambia nombre a conversador

**Comment by noauthoritybuturself** [comment]
ok,  both are fixed.
